### ISSUE TITLE
delocate-wheel do nothing on wheel

### ISSUE THREAD

**Issue by guyskk** [matthew-brett/delocate#15]
I'm building macosx wheels for lightpipes, the source code is:
https://github.com/guyskk/lightpipes/tree/wheels_for_macos

lightpipes need fftw, I install fftw by `brew install fftw`.
to build the wheel, run `pip install numpy` then `pip wheel --no-deps -w wheelhouse ./lightpipes` .
after that, I use delocate to fix the wheel:

```bash
➜  lightpipes git:(wheels_for_macos) delocate-listdeps --all  --depending wheelhouse/LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
/usr/lib/libSystem.B.dylib:
    LightPipes.so
/usr/lib/libc++.1.dylib:
    LightPipes.so
/usr/local/Cellar/fftw/3.3.6-pl1/lib/libfftw3.3.dylib:
    LightPipes.so
➜  lightpipes git:(wheels_for_macos) delocate-wheel -w wheelhouse_fixed -v wheelhouse/LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
Fixing: wheelhouse/LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
```

but it do nothing on the wheel:
```bash
➜  lightpipes git:(wheels_for_macos) ls wheelhouse_fixed
LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
➜  lightpipes git:(wheels_for_macos) ls -lh wheelhouse_fixed
total 176
-rw-r--r--  1 xiachufang  staff    86K  2 22 17:53 LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
➜  lightpipes git:(wheels_for_macos) ls -lh wheelhouse
total 176
-rw-r--r--  1 xiachufang  staff    86K  2 22 17:53 LightPipes-1.1.0-cp27-cp27m-macosx_10_10_x86_64.whl
```

**Comment by matthew-brett** [comment]
I think the problem is that your package has a single module at the top level (that goes in the `site-packages` directory, and delocate doesn't deal with this case - see https://github.com/matthew-brett/delocate/issues/12#issuecomment-246536098

To get delocate to work, you could reorganize your package like this:

```
setup.py
lightpipes/
    __init__.py
    LightPipes.pyx
    etc
```

where `__init__.py` does ``from .LightPipes import *``.   Actually that is the general pattern for Python packages, so might be good to do independent of delocate.

**Comment by guyskk** [comment]
This method works, thank you very much!
