### ISSUE TITLE
C extension module with no pure python files fails

### ISSUE THREAD

**Issue by isuruf** [matthew-brett/delocate#22]
[gmpy](https://github.com/aleaxit/gmpy) is a single C extension module with no pure python files. I'm using multibuild and it fails to copy the dependent libraries (libgmp, libmpfr, libmpc) to the wheel although delocate-listdeps correctly finds out that the dependent libraries need to be copied. (Also, `audit-wheel` on linux works perfectly.)

https://travis-ci.org/isuruf/gmpy2-wheels/jobs/250226653

**Comment by matthew-brett** [comment]
Yes, sorry about that - your problem, I believe is this : https://github.com/matthew-brett/delocate/issues/15

Could you see your way through to reorganizing to have a `gmpy2` package rather than a single `gmpy2.so` module?  As in something like:

```
gmpy2/
    __init__.py
```

where `__init__.py` contains "from ._gmpy2 import *" or similar.

**Comment by danielhers** [comment]
I would also appreciate if the libraries could be copied into `.../site-packages/.libs/copied_lib.dylib` when the modules are at the top level. In my case it's the [dynet](https://github.com/clab/dynet) library, which also doesn't use packages, and it would be quite complicated to change that. The Cython extension uses just `libdynet.dylib` (built externally), so there is no problem of name collision with other libraries.
Perhaps enable this as an option to `delocate-wheel`, to avoid cases where it is done by mistake?
E.g.

    delocate-wheel --allow-top-level  -v -w fixed-wheel dist/...
